FROM golang:1.22 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /app/api ./cmd/api

FROM alpine:3.20
COPY --from=build /app/api /app/api
EXPOSE 8080
ENTRYPOINT ["/app/api"]
