FROM golang:1.22 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /app/node ./cmd/node

FROM alpine:3.20
COPY --from=build /app/node /app/node
EXPOSE 9001
ENTRYPOINT ["/app/node"]
