FROM golang:1.22 AS build
#WORKDIR /src
#COPY . .
#RUN CGO_ENABLED=0 go build -o /app/trainer ./cmd/trainer

#FROM gcr.io/distroless/static-debian12
#COPY --from=build /app/trainer /app/trainer
#ENTRYPOINT ["/app/trainer"]
